### PR TITLE
Add bytesize docs

### PR DESCRIPTION
**Pull request by skryukov**

### CODE REVIEW

**Comment by solnic** [comment]
@skryukov could you rebuild this branch on top of `docsite-1.0` branch? doc updates should go to docsite branches first, then they can be merged into master, otherwise you can't really merge master to docsite branches because they have been created from tags.

**Comment by skryukov** [comment]
@solnic should I change the base from `master` to `docsite-1.0`?

**Comment by solnic** [comment]
@skryukov no, because `docsite-1.0` was created from `v1.0.0` tag, you need to checkout `docsite-1.0` and re-create your branch on top of it and f-push 😄

**Comment by skryukov** [comment]
@solnic done that already =)

**Comment by solnic** [comment]
@skryukov d'oooh sorry 😅 thanks!

**Pull request merged**
