### PR TITLE
Add bin folder

### LINKED ISSUE #30: Add bin/console
To facilitate new comers I think is a great idea to have and executable with everything loaded, so they can start playing around with `dry-logic`.

What do you think ?

### PR DESCRIPTION
**Pull request by GustavoCaso**
Fixes #30

Add bin folder with `console` script to load everything you to start playing with the library 🎉

### CODE REVIEW

**Comment by GustavoCaso** [comment]
@solnic can we merge this one?

**Comment by artofhuman** [comment]
@GustavoCaso I think we should change `executables` folder to `exe` in gemscpec.
https://github.com/dry-rb/dry-logic/blob/9d1ae6bc63e6c0a1bbd5159b3f9708f9eea5f7a3/dry-logic.gemspec#L13

as well as in dry-monads for example https://github.com/dry-rb/dry-monads/blob/master/dry-monads.gemspec#L25-L26

**Comment by GustavoCaso** [comment]
@artofhuman but the `bindir` is `bin` by default. In `dry-monads` is set to `exe` but the no `exe` folder in the project. Is that correct? Looks like we should change it in `dry-monads` as well.

Also why you think is better to name the folder `exe` just for curiosity.

**Comment by artofhuman** [comment]
Hm, i mean we should change `spec.executables` to
`spec.executables   = spec.files.grep(%r{^exe/}) { |f| File.basename(f) }` or remove this spec, 
because as bundle say

> If you use the --binstubs flag in [bundle install(1)][bundle-install], Bundler will automatically create a directory (which defaults to app_root/bin) containing all of the executables available from gems in the bundle.

**Comment by timriley** [comment]
@artofhuman is right, if we add this `bin/` dir with some utility scripts, we either want to remove `spec.executables = ...` from the gemspec or tell it to look in `exe/` instead of `bin/`.

Given that dry-logic is unlikely to ever ship its own executable, I think we could just remove it.

**Comment by GustavoCaso** [comment]
Thank you so much for the explanation @timriley and @artofhuman

**Pull request merged**
