### PR TITLE
Add match? predicate

### PR DESCRIPTION
**Pull request by flash-gordon**
@solnic I did this, but I'm very unsure now, this looks like too generic. Anyway, my class has a custom `===` method and I want to match values with that, soooo, can we have it? If not, just close :)

### CODE REVIEW

**Comment by solnic** [comment]
I find this very confusing, as you pointed out this feels too generic. ie when I see `match?` I think about regex, in fact I had no idea there's `Regex#===` that can be used against a string.

**Comment by timriley** [comment]
I wonder if it'd be clearer if we called it `#case?`

**Comment by solnic** [comment]
Yeah, I like this idea Tim. This does require you to understand how `case` statements work, but that's OK.

**Comment by flash-gordon** [comment]
OK, I like the idea, I updated the name. `Range` also has `#===` btw :)

**Pull request merged**
